### ISSUE TITLE
<b:commandButton> raises exception with "update='@all'"

### ISSUE THREAD

**Issue by zack-bergqvist** [TheCoder4eu/BootsFaces-OSP#1094]
The b:commandButton from BootsFaces is raising an exception while h:commandButton from the native JSF component does not. I am using ajax with "update='@all'".

This is the xhtml that I am using:
```
<h:head></h:head>
    <h:body>
        <h:form id="options">
            <h:inputText label="input" title="input" value="#{testBean.message}" />
            <div>
                <h:commandButton value="this works" action="#{testBean.submit}">
                    <f:ajax execute="@form" render="@all" />
                </h:commandButton>
                <b:commandButton value="this does not work"
                                    ajax="true"
                                    action="#{testBean.submit}"
                                    process="@form" update="@all" />
            </div>
            <div><h:outputText value="#{testBean.message}" /></div>
        </h:form>
    </h:body>
</html>
```
This is the full stack trace:
```
2019-08-30 18:18:52,711 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-2) Error Rendering View[/test.xhtml]: java.lang.IllegalStateException: CDATA tags may not nest
        at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.startCDATA(HtmlResponseWriter.java:714)
        at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:201)
        at javax.faces.context.PartialResponseWriter.startUpdate(PartialResponseWriter.java:221)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:637)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1736)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:424)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:343)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1124)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:639)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1736)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:424)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:343)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1124)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:465)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:748)
```
And last but not least this is the backing that I am using:
```
@Named("testBean")
@RequestScoped
public class TestBean {

    private String msg = null;

    public void setMessage(final String msg) {
        this.msg = msg;
    }

    public String getMessage() {
        return msg;
    }

    public void submit() {
        //do some business logic here
    }
}
```
I am using BootsFaces 1.4.1 with Wildfly 14.0.1.

**Comment by stephanrauh** [comment]
Additional information: [this StackOverflow discussion](https://stackoverflow.com/questions/57736767/why-is-bcommandbutton-raising-exception)

It seems to be a general problem. I've managed to reproduce it with Liberty Profile 18 running on MyFaces, too. A first hour of debugging indicates that after rendering everything, the `UIViewRoot` is rendered again. How is that possible?

**Comment by stephanrauh** [comment]
Currently, we're short of committers. So I suggest you simply avoid `@all`. JSF offers `update="@all"`, but it's always been error-prone.
