### ISSUE TITLE
bootsfaces.net Null Pointer Exception

### ISSUE THREAD

**Issue by jamestenglish** [TheCoder4eu/BootsFaces-OSP#204]
Not directly related to the project but several pages on bootsfaces.net are inaccessible with a Null Pointer Exception:

http://www.bootsfaces.net/layout/panels.jsf
```
An Error Occurred:

java.lang.NullPointerException
- Stack Trace

java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:2399)
	at de.beyondjava.angularFaces.core.transformation.AttributeUtilities.getAttribute(AttributeUtilities.java:35)
	at de.beyondjava.angularFaces.core.transformation.TranslationCallback.translateAttribute(TranslationCallback.java:76)
	at de.beyondjava.angularFaces.core.transformation.TranslationCallback.visit(TranslationCallback.java:64)
	at de.beyondjava.angularFaces.core.transformation.FullVisitContext.invokeVisitCallback(FullVisitContext.java:106)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at de.beyondjava.angularFaces.core.transformation.PuiAngularTransformer$4.run(PuiAngularTransformer.java:101)
	at de.beyondjava.angularFaces.core.transformation.PuiAngularTransformer.time(PuiAngularTransformer.java:268)
	at de.beyondjava.angularFaces.core.transformation.PuiAngularTransformer.processEvent(PuiAngularTransformer.java:99)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)
	at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2169)
	at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2142)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:301)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:245)
	at org.jboss.as.jsf.injection.weld.ForwardingApplication.publishEvent(ForwardingApplication.java:299)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:107)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
+ Component Tree

+ Scoped Variables

08-Nov-2015 18:58:33 - Generated by Mojarra/Facelets
```

**Comment by stephanrauh** [comment]
@TheCoder4eu Riccardo, can you remove the class attribute from pageTemplate.xml, line 45? That should fix the error.

@jamestenglish Basically, it's a problem of AngularFaces. Seems like Apache MyFaces has made an attribute read-only that previously could be overwritten.

**Comment by TheCoder4eu** [comment]
Thank you. Now the website Looks ok again.
Probem is fixed with next release.
