### ISSUE TITLE
bsf load error

### ISSUE THREAD

**Issue by pavankd** [TheCoder4eu/BootsFaces-OSP#395]
Hi am getting following error.Please help me

WARNING: JSF1064: Unable to find or serve resource, css/bootstrap/bsf.css, from library, bsf.
Jun 03, 2016 5:20:04 PM com.sun.faces.context.ExceptionHandlerImpl log
1100: JSF1073: javax.faces.FacesException caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message=Error loading theme, cannot find "css/bootstrap/bsf.css" resource of "bsf" library
Jun 03, 2016 5:20:04 PM com.sun.faces.context.ExceptionHandlerImpl log
1100: Error loading theme, cannot find "css/bootstrap/bsf.css" resource of "bsf" library
javax.faces.FacesException: Error loading theme, cannot find "css/bootstrap/bsf.css" resource of "bsf" library
	at net.bootsfaces.listeners.AddResourcesListener.loadTheme(AddResourcesListener.java:295)
	at net.bootsfaces.listeners.AddResourcesListener.addJavascript(AddResourcesListener.java:152)
	at net.bootsfaces.listeners.AddResourcesListener.processEvent(AddResourcesListener.java:93)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)
	at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2187)
	at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2163)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:303)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:247)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:107)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.sysintelli.chemrsa.mbean.util.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhedar** [comment]
It seems like you may have mixed up web.xml configurations.

I guess you are using PrimeFaces and wanted to set the `bootstrap` theme. However, BootsFaces doesn't contain a theme with such a name. How does your web.xml look like?

To get rid of this error, you should probably remove the theme parameter are set up a valid theme:

    <context-param>
        <param-name>BootsFaces_THEME</param-name>
        <param-value>cerulean</param-value>
    </context-param>


See the [theme section](http://showcase.bootsfaces.net/layout/themes.jsf) of the showcase for more information.

**Comment by pavankd** [comment]
thank you zhedar.
