### ISSUE TITLE
Add initial Bootswatch Themes support

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#40]
Add support for building BootsFaces with one of the Bootswatch Themes:

http://bootswatch.com/

cerulean,  darkly   flatly, journal,  paper, sandstone,  slate, superhero,  united,
cosmo, cyborg,  lumen, readable,  simplex, spacelab, yeti.

Work for more advanced support will be done in #182 .

**Comment by stephanrauh** [comment]
+1

**Comment by bilak** [comment]
+1 and https://wrapbootstrap.com also

**Comment by exabrial** [comment]
+1 for bootswatch. thanks!

**Comment by TheCoder4eu** [comment]
wip

**Comment by TheCoder4eu** [comment]
Step 1: modify bs-*.less files to import custom variables and theme .less files

**Comment by TheCoder4eu** [comment]
Wip on Step 2: add config settings for Bootswatch theme and sub-version (e.g. v3.3.5+4 : sub-version would be '+4')
Wip on Step 3: modify Gradle build to fetch Bootswatch files and copy relevant files for building based on configuration

**Comment by TheCoder4eu** [comment]
Step 4: Testing build
WIP

**Comment by TheCoder4eu** [comment]
Building seems working without problems until Bootswatch v3.3.5+2 .
After that, Bootswatch team has introduced in the Themes requiring a Font, a variable for the URL to allow overriding it by projects that build on it ( see Issue thomaspark/bootswatch#507 ).
The code is , for example:
```
@web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700";

.fonts(@path) {
  @import url("@{path}");
}
.fonts(@web-font-path);
```
but this seems not to be supported by the Gradle plugin I chose to process .less files , bertramdev/asset-pipeline or by less4j , this is the error I get : 
```
Caused by: java.lang.NullPointerException
        at com.github.sommeri.less4j.core.compiler.stages.SingleImportSolver.importEncountered(SingleImportSolver.java:98)
        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.importIntoPlaceholder(ImportsAndScopeSolver.java:52)
        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports(ImportsAndScopeSolver.java:41)
        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports(ImportsAndScopeSolver.java:43)
        at com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.buildImportsAndScope(ImportsAndScopeSolver.java:34)
        at com.github.sommeri.less4j.core.compiler.LessToCssCompiler.resolveImportsAndReferences(LessToCssCompiler.java:95)
        at com.github.sommeri.less4j.core.compiler.LessToCssCompiler.compileToCss(LessToCssCompiler.java:47)
        at com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.doCompile(ThreadUnsafeLessCompiler.java:86)
        at com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.compile(ThreadUnsafeLessCompiler.java:76)
        at com.github.sommeri.less4j.LessCompiler$compile.call(Unknown Source)
        at asset.pipeline.less.Less4jProcessor.process(Less4jProcessor.groovy:27)
        ... 117 more


```
I'll check if this is legal syntax and eventually submit an Issue.
For now it will suffice to use v3.3.5+2 for themes with font url, v3.3.5+n , n>2 for the others.

**Comment by TheCoder4eu** [comment]
Tests finished successfully, I just need to add a patch to support Bootswatch versions > v3.3.5+2 .

**Comment by TheCoder4eu** [comment]
I am testing the patch to support Bootswatch versions > v3.3.5+2 .

**Comment by TheCoder4eu** [comment]
Everything is OK.
