### ISSUE TITLE
BsfUtils, ClassNotFoundException for Base64  (v0.9.0)

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#452]
Hi,

New version of BsfUtils (v0.9.0) has a dependence with java.util.Base64 which is only in jdk 1.8.
It implies a java.lang.ClassNotFoundException for exemple when rendering a b:tree on a former jdk (1.7):
did i miss something ?

(default task-10) java.lang.NoClassDefFoundError: java/util/Base64
	at net.bootsfaces.utils.BsfUtils.toString(BsfUtils.java:551)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderNode(TreeModelUtils.java:186)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderSubnodes(TreeModelUtils.java:209)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderNode(TreeModelUtils.java:182)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderSubnodes(TreeModelUtils.java:209)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderNode(TreeModelUtils.java:182)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderSubnodes(TreeModelUtils.java:209)
	at net.bootsfaces.component.tree.model.TreeModelUtils.renderModelAsJson(TreeModelUtils.java:126)
	at net.bootsfaces.component.tree.TreeRenderer.encodeEnd(TreeRenderer.java:157)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
...

**Comment by stephanrauh** [comment]
It seems this error slipped through our QA efforts. What does this error mean to you? Is only the tree affected, or is BootsFaces broken altogether on Java 6 and 7?

**Comment by Kristover** [comment]
For me it's a regression :
Running on wildfly 9.0.2 with jdk 1.7 for sample on my config, proceed into the specified stacktrace and the page is not displayed. 
All components that depends on BsfUtils are concerned (DateTimePicker, Badge, PillLinks, Tree, etc...)
It's not a problem on dev environment because we can adapt. But in production env, it implies to migrate the jdk environment...

**Comment by stephanrauh** [comment]
You won't have to migrate anything in production :). I'm sure we'll be able to fix the bug pretty soon,

**Comment by zhedar** [comment]
I just ran a quick check with the animal sniffer plugin and it didn't find this incompatibility... This somehow bothers me quite a bit, as there doesn't to be a reliant way to find those problems. Well... alteast not without having to manually switch to JDK6 or 7 each time.

**Comment by stephanrauh** [comment]
I've just pushed a different version of the code to the developer preview snapshot repository of Maven Central. I believe this doesn't require Java 8. 

Download coordinates:

```xml
   <dependency>
      <groupId>net.bootsfaces</groupId>
      <artifactId>bootsfaces</artifactId>
      <version>0.9.1-SNAPSHOT</version>
    </dependency>
```

**Comment by Kristover** [comment]
Hi again,

just fyi,
using 0.9.1-SNAPSHOT correct the problem and works now (pages displayed)

Thanks for your reactivity.
Regards

**Comment by stephanrauh** [comment]
THX!
