### ISSUE TITLE
b:tree didn't work after using version 0.9.0

### ISSUE THREAD

**Issue by luciomail** [TheCoder4eu/BootsFaces-OSP#456]
Hi guys,

I'm having some trouble with component <b:tree>.
I was using bootsfaces v0.8.6, but when i changed the version to v0.9.0, the component stopped working.

i tried a simple example as below, but nothing.

		DefaultNodeImpl categoriasModelTree = new DefaultNodeImpl("root");
		DefaultNodeImpl filho = new DefaultNodeImpl("Teste 1");
		categoriasModelTree.withSubnode(filho);

		DefaultNodeImpl filho2 = new DefaultNodeImpl("Teste 2");
		categoriasModelTree.withSubnode(filho2);

I don't know what happened. But when i change back to v0.8.6, it works fine.
Help me.

**the message error is:**
16:36:11,644 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/dissidioColetivo].[Faces Servlet]] (http-localhost/127.0.0.1:8080-20) JBWEB000236: Servlet.service() for servlet Faces Servlet threw exception: java.lang.IllegalStateException: CDATA tags may not nest
	at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.startCDATA(HtmlResponseWriter.java:667) [jsf-impl-2.1.28.redhat-9.jar:2.1.28.redhat-9]
	at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:172) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
	at javax.faces.context.PartialResponseWriter.startError(PartialResponseWriter.java:342) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
	at org.primefaces.context.PrimePartialResponseWriter.startError(PrimePartialResponseWriter.java:190) [primefaces-5.2.jar:5.2]
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handlePartialResponseError(AjaxExceptionHandlerImpl.java:202) [jsf-impl-2.1.28.redhat-9.jar:2.1.28.redhat-9]
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handle(AjaxExceptionHandlerImpl.java:126) [jsf-impl-2.1.28.redhat-9.jar:2.1.28.redhat-9]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119) [jsf-impl-2.1.28.redhat-9.jar:2.1.28.redhat-9]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139) [jsf-impl-2.1.28.redhat-9.jar:2.1.28.redhat-9]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at br.jus.trt9.dissidioColetivo.web.filter.AuthorizedFilter.doFilter(AuthorizedFilter.java:55) [classes:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at br.jus.trt9.dissidioColetivo.filter.IELixaoCompatablityFixFilter.doFilter(IELixaoCompatablityFixFilter.java:21) [classes:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at br.jus.trt9.dissidioColetivo.filter.AuthorizedFilter.doFilter(AuthorizedFilter.java:55) [classes:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:71) [cas-client-core-3.4.1.jar:3.4.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:236) [cas-client-core-3.4.1.jar:3.4.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:155) [cas-client-core-3.4.1.jar:3.4.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.logging.log4j.core.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:66) [log4j-core-2.0-rc1.jar:2.0-rc1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.2.Final-redhat-2.jar:7.5.2.Final-redhat-2]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.2.Final-redhat-2.jar:7.5.2.Final-redhat-2]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.2.Final-redhat-2.jar:7.5.2.Final-redhat-2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:355) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:911) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at org.apache.tomcat.util.net.NioEndpoint$ChannelProcessor.run(NioEndpoint.java:936) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_51]
	at org.apache.tomcat.util.net.NioEndpoint$DefaultThreadFactory$1$1.run(NioEndpoint.java:1249) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]

**Comment by stephanrauh** [comment]
According to the stacktrace, the error message occurs when JSF tries to report an AJAX error. Do you have another stacktrace containing the root cause?

BTW, if you're using Java 7 or below, just switch to the developer preview BootsFaces 0.9.1-SNAPSHOT. See #369 on how to get it (and don't forget to update the version numbers).

**Comment by TheCoder4eu** [comment]
@luciomail did using 0.9.1 solve your issue?

**Comment by luciomail** [comment]
Hi, sorry for being slow to respond.

Yes, it's working. I had to implement the methods (processValueChecked and processValueUnchecked) from TreeNodeEventListener interface and now the component is doing what i want.
I thought the processing of check and uncheck the items would be automatic, but i had to use these methods like below:

	public void processValueChecked(TreeNodeCheckedEvent arg0) {
		Node node = (DefaultNodeImpl) arg0.getNode();
		node.setChecked(true);

		TreeModelUtils.updateNodeById(getCategoriasModelTree(), node.getNodeId(), node);
	}

But, thanks for helping.

**Comment by TheCoder4eu** [comment]
@luciomail thanks for your feedback, we'll improve the b:tree Documentation.
