### ISSUE TITLE
b:selectOneMenu doesn't cope with HashMaps

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#776]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:b="http://bootsfaces.net/ui">
<f:view contentType="text/html">
	<h:head>
		<title>test</title>
		<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
	</h:head>
	<h:body>
		<h:form id="loginForm">
			<b:container layout="fluid">
				<b:panel title="paneltitle" look="info" id="panel1">
					<b:row>
						<b:column medium-screen="4">
						<b:selectOneMenu value="#{carPool.hashPool}" id="country"
							ajax="true" onchange="ajax:carPool.onSelect()"
							update="@Form">
							<f:selectItem itemLabel="Please select" itemValue="0" />
							<f:selectItems value="#{carPool.hashPool.entrySet()}"
								var="entry" itemValue="#{entry.key}" itemLabel="#{entry.value}" />
						</b:selectOneMenu>
						</b:column>
					</b:row>
				</b:panel>
			</b:container>
		</h:form>
	</h:body>
</f:view>
</html>
````

Java:
```xml
	Map hashPool = new HashMap();
	public Map getHashPool() {
		if (hashPool.isEmpty()) {
			hashPool.put("Honda", "first");
			hashPool.put("Opel", "second");
		}
		return this.hashPool;
	}
```

Selecting an entry causes this server side error:
```
may 12, 2017 5:44:49 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
GRAVE: javax.faces.component.UpdateModelException: javax.el.ELException: /test.xhtml @28,23 value="#{carPool.hashPool}": No puedo convertir Honda desde tipo class java.lang.String a interface java.util.Map
	at javax.faces.component.UIInput.updateModel(UIInput.java:866)
	at javax.faces.component.UIInput.processUpdates(UIInput.java:749)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291)
	at javax.faces.component.UIForm.processUpdates(UIForm.java:281)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1254)
	at com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.ELException: /test.xhtml @28,23 value="#{carPool.hashPool}": No puedo convertir Honda desde tipo class java.lang.String a interface java.util.Map
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:139)
	at javax.faces.component.UIInput.updateModel(UIInput.java:832)
	... 34 more
Caused by: javax.el.ELException: No puedo convertir Honda desde tipo class java.lang.String a interface java.util.Map
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:553)
	at org.apache.el.parser.AstValue.setValue(AstValue.java:203)
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:257)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
	... 35 more
```

**Comment by muhammedf** [comment]
What does this supposed to mean:

> selectOneMenu value="#{carPool.hashPool}"

Is not this value have to be in type of itemValue?

**Comment by stephanrauh** [comment]
Oh. Maybe that's why it didn't work. I'll have to check it again. Let's hope it's a false positive!

**Comment by stephanrauh** [comment]
OK, this bug was a false positive.
