### ISSUE TITLE
EL error on UI:PARAM

### ISSUE THREAD

**Issue by cooper-lyt** [TheCoder4eu/BootsFaces-OSP#882]
class:
`class Job { private String name;  // get and set }`
`class Person {private Job job; // get and set }`

page person.xhtml:
`<b:inputText value="#{_param.job.name}"/>`
page use.xhtml
'<ui:include src="person.xhtml">
                <ui:param name="_param" value="#{person}"/>
  </ui:include>'

`javax.el.PropertyNotFoundException: Target Unreachable, identifier '_param' resolved to null`

**Comment by ggam** [comment]
If you remove the inputText and put `<h:outputText value="#{_param.job.name}" />` does the problem persist? It's just to discard other problems

**Comment by cooper-lyt** [comment]
h:outputText  and h:inputText is no problem!

**Comment by cooper-lyt** [comment]
Caused by: javax.el.PropertyNotFoundException: Target Unreachable, identifier '_param' resolved to null
	at com.sun.el.parser.AstValue.getTarget(AstValue.java:174)
	at com.sun.el.parser.AstValue.getValueReference(AstValue.java:101)
	at com.sun.el.ValueExpressionImpl.getValueReference(ValueExpressionImpl.java:213)
	at org.jboss.weld.util.el.ForwardingValueExpression.getValueReference(ForwardingValueExpression.java:86)
	at org.jboss.weld.util.el.ForwardingValueExpression.getValueReference(ForwardingValueExpression.java:86)
	at net.bootsfaces.beans.ELTools.evalAsObject(ELTools.java:120)
	at net.bootsfaces.beans.ELTools.getField(ELTools.java:202)
	at net.bootsfaces.beans.ELTools.readAnnotations(ELTools.java:354)
	at net.bootsfaces.beans.ELTools.readAnnotations(ELTools.java:376)
	at net.bootsfaces.render.CoreRenderer.getErrorAndRequiredClass(CoreRenderer.java:187)
	at net.bootsfaces.component.inputText.InputTextRenderer.generateStyleClass(InputTextRenderer.java:472)
	at net.bootsfaces.component.inputText.InputTextRenderer.encodeEnd(InputTextRenderer.java:211)

**Comment by chongma** [comment]
Could this be related to #846 ?  If so it should be fixed in 1.2.0...

Also, have you tried not prefixing the `ui:param` name with an underscore?  e.g. `<ui:param name="person" value="#{person}"/>`

Also have you considered composite components instead of ui:include?  See this recent article by Stephan: https://www.beyondjava.net/blog/angular-components-successful-jsf-components/

**Comment by cooper-lyt** [comment]
i try no underscore, same problems  

use `<b:inputText value="#{_param.name}"/>  ` is ok 
but  use `<b:inputText value="#{_param.job.name}"/>  `  get a error

**Comment by chongma** [comment]
maybe you could try 1.2.0-SNAPSHOT #369 ?

**Comment by cooper-lyt** [comment]
i try 1.2.0-SNAPSHOT 

Caused by: javax.faces.FacesException: Cannot remove the same component twice: j_idt10

this page in 1.1.3 is fine!

**Comment by ggam** [comment]
@cooper-lyt I've tried to reproduce it locally but I couldn't. Attached is the application I've created to test it.
[include-error.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/1398495/include-error.zip)

Could you please provide us a sample reproducer?

**Comment by stephanrauh** [comment]
After receiving no response after such a long time, let's close the ticket.
