### ISSUE TITLE
<b:selectBooleanCheckbox> with Primitive types cause a NullPointerException in CdiUtils.createConverter

### ISSUE THREAD

**Issue by knoppt** [TheCoder4eu/BootsFaces-OSP#956]
Upgrade to BootsFaces Version 1.2.0 and Mojarra 2.3.5.SP1 

I get a NPE in CDIUtils class when a primitive boolean value was expected in backingbean setter method for b:selectBooleanCheckbox.
 
When using Boolean Wrapper Class it works like a charme.
There is no problem when using bootsfaces Version 1.0.2 with primitive boolean type!

Is it a bug in mojarra or in bootsfaces?
[Mojarra bug 4367](https://github.com/javaserverfaces/mojarra/issues/4367)

```
Stacktrace: 
java.lang.NullPointerException
at com.sun.faces.cdi.CdiUtils.createConverter(CdiUtils.java:125)
at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:1458)
at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:425)
at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:425)
at org.apache.deltaspike.jsf.impl.injection.InjectionAwareApplicationWrapper.createConverter(InjectionAwareApplicationWrapper.java:60)
at net.bootsfaces.render.CoreRenderer.resolveConverter(CoreRenderer.java:559)
at net.bootsfaces.render.CoreRenderer.getConvertedValue(CoreRenderer.java:530)
at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1122)
at javax.faces.component.UIInput.validate(UIInput.java:1030)
at javax.faces.component.UIInput.executeValidate(UIInput.java:1334)
at javax.faces.component.UIInput.processValidators(UIInput.java:757)
at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:632)
at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1736)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIForm.visitTree(UIForm.java:395)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:424)
at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:285)
at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1330)
at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:77)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.execute(DeltaSpikeLifecycleWrapper.java:89)
at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:97)
at etm.contrib.integration.jee.jsf.DelegatingEtmLifecycleFactory$InterceptedLifeCycle.execute(DelegatingEtmLifecycleFactory.java:103)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at de.rlp.statistik.wahlen.filter.SecurityFilter.doFilter(SecurityFilter.java:47)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 



```

**Comment by stephanrauh** [comment]
Difficult to say. There are many libraries involved: PrimeFaces, DeltaSpike, CDI, and us. The offending source code looks innocent enough, at least on the BootsFaces side:

```java
if (valType != null) {
	return context.getApplication().createConverter(valType);
}
```

Would you mind to send us a minimal, viable, and working demo? BootsFaces is a leisure time project, so we'd appreciate a really simple demo. In particular, we don't want to set up a database.

Thanks in advance,
Stephan

**Comment by knoppt** [comment]
Hi, 
here is my sampleProject:
[](https://github.com/knoppt/bootsfacesSample)

Hope your can verify the error! 
Thanks, Torsten

**Comment by knoppt** [comment]
[https://github.com/knoppt/bootsfacesSample](url)

**Comment by stephanrauh** [comment]
Hi Torsten, 

thanks for providing us such a nice minimal, viable reproducer! It's just great, and it allowed me to reproduce the bug without a the pain. Well, apart from installing Wildfly 13, finding out how to activate JSF 2.3, and how to debug the source code which is hosted at a JBoss repository. But that the inevitable chore :). 

Cutting a long story short: great job!

Stephan

**Comment by stephanrauh** [comment]
Well, this looks definitely like a Mojarra bug. They try to find the super class without considering that the super class of primitive types is null.

Remains the question whether we, the BootsFaces team, can do something about it.

**Comment by stephanrauh** [comment]
I've prepared a workaround. I imagine there's never a converter for a primitive data type. But I'm not sure, and the testing process of BootsFaces 1.3 has already begun, so let's ponder about this question meticulously.

**Comment by stephanrauh** [comment]
I've pushed the workaround to GitHub. It'll be part of BootsFaces 1.3.0. We've already started to prepare BootsFaces 1.3.0. If all goes well, you'll get your bugfix soon.

**Comment by stephanrauh** [comment]
@knoppt I've uploaded a developer preview version of BootsFaces 1.3.0-SNAPSHOT to Maven Central. See #369 how to get it. Would you mind to run a test and to tell us if the bug has been solved?

**Comment by LisaFlorian** [comment]
Hi,

I'm a coworker of knoppt.
I just tested your bugfix in our project and the bug has been solved.

Thanks for your help.
