### ISSUE TITLE
NullPointerException with b:icon

### ISSUE THREAD

**Issue by joepal1976** [TheCoder4eu/BootsFaces-OSP#971]
I have a very simple test case:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<title>Test</title>	
</h:head>
<h:body>
	<b:icon value="cloud" />		 
</h:body>
</html>
```

Running this causes a NullPointerException:

```
ALLVARLIG: Error Rendering View[/test.xhtml]
java.lang.NullPointerException
        at net.bootsfaces.component.icon.IconRenderer.encodeIcon(IconRenderer.java:144)
        at net.bootsfaces.component.icon.IconRenderer.encodeBegin(IconRenderer.java:95)
        at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:865)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1854)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.dcab.simchild.CacheFilter.doFilter(CacheFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

The same happens when using iconAwesome, but _not_ when using icons in parameters to, for example, navlink. 

This is running bootsfaces 1.2.0 on tomcat 8.0.32 with com.sun.faces jsf-impl/jsf-api 2.2.15.

**Comment by joepal1976** [comment]
Upgrading to 1.3.0 solves the issue. I'm thus going to assume it was something known and fixed.

**Comment by stephanrauh** [comment]
Indeed. We've added the `value` attribute in BootsFaces 1.3.0, because so many developers use it instinctively. Before 1.3.0, you had to use the attribute `name`. Now, both attributes are synonyms.
