### ISSUE TITLE
Exception :  The size of b:panel must be one of the values xs, sm...

### ISSUE THREAD

**Issue by rac021** [TheCoder4eu/BootsFaces-OSP#985]
Hi, 

I have the following code : 

```
 <b:panel visible="#{fn:contains(myBean.enabledSecurity(), 'custom')}"  >
     <b:row>
          <ez:authentication_checker  id="checkerCommand" />
      </b:row>
   </b:panel>
                    
  <b:panel visible="#{fn:contains(myBean.enabledSecurity(), 'sso')}" >
     <b:row>
             <ez:authentication_sso_checker  id="checkerCommand_sso" />
       </b:row>
  </b:panel> 
```

Opening the page gives me the following exception :

Caused by: javax.faces.FacesException: The size of b:panel must be one of the values xs, sm, md, lg, tiny-screen, small-screen, medium-screen, or large-screen
	at net.bootsfaces.render.Responsive.translateSize(Responsive.java:304)
	at net.bootsfaces.render.Responsive.evaluateExpression(Responsive.java:237)
	at net.bootsfaces.render.Responsive.encodeVisibility(Responsive.java:118)
	at net.bootsfaces.render.Responsive.getResponsiveStyleClass(Responsive.java:93)
	at net.bootsfaces.component.panel.PanelRenderer.encodeBegin(PanelRenderer.java:103)
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:865)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1854)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)

 Can anyone tells me what's wrong ?

Thanks

R

**Comment by stephanrauh** [comment]
Looks like a real bug to me. Plus, it doesn't seem to be new. Which version of BootsFaces are you using?

**Comment by rac021** [comment]
Yes , replacing visible by rendered. works for me.

Thank you

R
